version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./volumes/db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: backend
    command: bash -c "python manage.py collectstatic --noinput ; python manage.py runserver_plus 0.0.0.0:8000"
    volumes:
      - ./backend:/code
      - ./volumes/static_volume:/static_volume
      - ./volumes/media_volume:/media_volume
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db

  frontend:
    build: frontend
    command: ionic serve --external --lab --lab-host=0.0.0.0

    volumes:
      - ./frontend:/code
    ports:
      - "127.0.0.1:8100:8100"
      - "127.0.0.1:8200:8200"

  nginx:
    build: nginx
    ports:
      - 1337:80
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/static_volume:/static_volume
      - ./volumes/media_volume:/media_volume
