version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./volumes/db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"

  backend:
    build: backend
    command: bash -c "python manage.py collectstatic --noinput ; uwsgi --socket :8000 -b 131072 --processes 2 --threads 2 --module piraterace.wsgi"
    volumes:
      - ./backend:/code
      - ./volumes/static_volume:/static_volume
      - ./volumes/media_volume:/media_volume
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    build: nginx
    ports:
      - 127.0.0.1:1337:80
    depends_on:
      - backend
    volumes:
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/static_volume:/static_volume
      - ./volumes/media_volume:/media_volume
      - ./frontend/www:/www

  redis:
    image: 'bitnami/redis:latest'
    expose:
      - "6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
