# Generated by Django 3.2 on 2021-04-18 21:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player_count', models.PositiveSmallIntegerField(default=8)),
                ('player_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None)),
                ('player_pos', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=2), size=None)),
                ('player_moves', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5), size=None)),
            ],
        ),
    ]
