# Generated by Django 4.0.7 on 2022-09-28 08:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pigame", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "deck",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None
                    ),
                ),
                ("next_card", models.PositiveSmallIntegerField(default=0)),
                ("time_submitted", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="pigame.basegame"),
                ),
            ],
        ),
    ]
