# Generated by Django 4.0.7 on 2026-06-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piplayer', '0002_account_gameconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='account',
            name='gameconfig',
        ),
        migrations.RemoveField(
            model_name='account',
            name='next_card',
        ),
    ]
