# Generated by Django 4.0.7 on 2026-06-13 20:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameconfig',
            old_name='allow_transfer',
            new_name='path_highlighting',
        ),
        migrations.RenameField(
            model_name='gameconfig',
            old_name='player_teams',
            new_name='player_next_card',
        ),
        migrations.RemoveField(
            model_name='basegame',
            name='mapfile',
        ),
        migrations.RemoveField(
            model_name='basegame',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='gameconfig',
            name='nlives',
        ),
        migrations.RemoveField(
            model_name='gameconfig',
            name='npause_on_destroy',
        ),
        migrations.RemoveField(
            model_name='gameconfig',
            name='npause_on_repair',
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='gamename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='percentage_repaircards',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='player_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='request_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
