# Generated by Django 4.0.7 on 2026-06-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigame', '0002_rename_allow_transfer_gameconfig_path_highlighting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='treasure_preview',
            field=models.BooleanField(default=True),
        ),
    ]
